install! 'cocoapods',
:share_schemes_for_development_pods => true

use_frameworks! :linkage => :static

use_modular_headers!

platform :ios, '9.0'

target 'Globalalise_Tests' do
  pod 'Globalalise', :path => '../'
  
  
end
